# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9NpRjm_2STQWztNXD5dRRLH4YUJukkG
"""

from mirrorball.class_sc_filter import sc_filter